// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPreview() {
  return window['go']['main']['App']['ClearPreview']();
}

export function CopyCalibrationReport() {
  return window['go']['main']['App']['CopyCalibrationReport']();
}

export function CopyLast20Frames() {
  return window['go']['main']['App']['CopyLast20Frames']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetFontScale() {
  return window['go']['main']['App']['GetFontScale']();
}

export function GetHideAuthor() {
  return window['go']['main']['App']['GetHideAuthor']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetResourceStats() {
  return window['go']['main']['App']['GetResourceStats']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function IsFirstLaunch() {
  return window['go']['main']['App']['IsFirstLaunch']();
}

export function MarkFirstLaunchDone() {
  return window['go']['main']['App']['MarkFirstLaunchDone']();
}

export function OpenLiveDebugWindow() {
  return window['go']['main']['App']['OpenLiveDebugWindow']();
}

export function PlaySystemSound(arg1) {
  return window['go']['main']['App']['PlaySystemSound'](arg1);
}

export function PreviewMatrix(arg1) {
  return window['go']['main']['App']['PreviewMatrix'](arg1);
}

export function ResetAHRS() {
  return window['go']['main']['App']['ResetAHRS']();
}

export function ResetGyroFilter() {
  return window['go']['main']['App']['ResetGyroFilter']();
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetFontScale(arg1) {
  return window['go']['main']['App']['SetFontScale'](arg1);
}

export function SetHideAuthor(arg1) {
  return window['go']['main']['App']['SetHideAuthor'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetTuningActive(arg1) {
  return window['go']['main']['App']['SetTuningActive'](arg1);
}

export function SetTuningFilterParams(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTuningFilterParams'](arg1, arg2, arg3);
}

export function SetWindowTheme(arg1) {
  return window['go']['main']['App']['SetWindowTheme'](arg1);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture(arg1) {
  return window['go']['main']['App']['StopCapture'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function ValidateCalibration(arg1, arg2) {
  return window['go']['main']['App']['ValidateCalibration'](arg1, arg2);
}

export function ValidateSync() {
  return window['go']['main']['App']['ValidateSync']();
}
