// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function ValidateSync() {
  return window['go']['main']['App']['ValidateSync']();
}
