// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPreview() {
  return window['go']['main']['App']['ClearPreview']();
}

export function CopyCalibrationReport() {
  return window['go']['main']['App']['CopyCalibrationReport']();
}

export function CopyLast20Frames() {
  return window['go']['main']['App']['CopyLast20Frames']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function PreviewMatrix(arg1) {
  return window['go']['main']['App']['PreviewMatrix'](arg1);
}

export function ResetAHRS() {
  return window['go']['main']['App']['ResetAHRS']();
}

export function SaveProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2, arg3);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture(arg1) {
  return window['go']['main']['App']['StopCapture'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function ValidateCalibration(arg1, arg2) {
  return window['go']['main']['App']['ValidateCalibration'](arg1, arg2);
}

export function ValidateSync() {
  return window['go']['main']['App']['ValidateSync']();
}
