// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLanguages():Promise<Array<string>>;

export function GetState():Promise<main.AppState>;

export function GetTranslations(arg1:string):Promise<string>;

export function TogglePause():Promise<main.AppState>;

export function ValidateSync():Promise<Array<string>>;
