// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearPreview():Promise<void>;

export function CopyCalibrationReport():Promise<string>;

export function CopyLast20Frames():Promise<string>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetHideAuthor():Promise<boolean>;

export function GetLang():Promise<string>;

export function GetLanguages():Promise<Array<string>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetResourceStats():Promise<Record<string, any>>;

export function GetState():Promise<main.AppState>;

export function GetTheme():Promise<string>;

export function GetTranslations(arg1:string):Promise<string>;

export function IsFirstLaunch():Promise<boolean>;

export function MarkFirstLaunchDone():Promise<void>;

export function OpenLiveDebugWindow():Promise<void>;

export function PreviewMatrix(arg1:any):Promise<void>;

export function ResetAHRS():Promise<void>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<Record<string, any>>;

export function SaveProfile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:any):Promise<string>;

export function SetActiveProfile(arg1:number):Promise<string>;

export function SetHideAuthor(arg1:boolean):Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetWindowTheme(arg1:string):Promise<void>;

export function StartCapture():Promise<void>;

export function StopCapture(arg1:number):Promise<main.CaptureResult>;

export function TogglePause():Promise<main.AppState>;

export function ValidateCalibration(arg1:any,arg2:any):Promise<main.ValidationResult>;

export function ValidateSync():Promise<Array<string>>;
