// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceStatus():Promise<boolean>;

export function OpenInFolder(arg1:string):Promise<void>;

export function ResetAHRS():Promise<void>;

export function SaveCSVFile(arg1:string,arg2:string):Promise<string>;

export function SetWindowTheme(arg1:string):Promise<void>;
